### ISSUE TITLE
aliasDangerous crashing on Mac

### ISSUE THREAD

**Issue by omerts** [oklas/react-app-rewire-alias#34]
Hi,

Thanks for the great plugin,  we are getting the following error on a Mac when trying to use aliasDangerous for having a common shared project:
```
request.descriptionFileRoot.indexOf('/node_modules/') !== -1 ||
                                      ^

TypeError: Cannot read property 'indexOf' of undefined
```
Printing the request object we get the following:
```
{"context":{"issuer":"/Users/NothingButOne/develop/GophOR/packages/common/redux/actions/index.ts"},"path":"/Users/NothingButOne/develop/GophOR/packages/common/redux/actions/pushActions","query":"","module":false,"file":false}
```

Our project structure is:
- packages
-- common
-- web

Inside web we are referencing common, this is our config:
```
const path = require('path')
const {
  aliasDangerous,
  aliasJest,
} = require('react-app-rewire-alias/lib/aliasDangerous')

const aliasMap = {
  '@common': path.resolve(__dirname, '../common'),
}

module.exports = aliasDangerous(aliasMap)
module.exports.jest = aliasJest(aliasMap)
```

**Comment by oklas** [comment]
Hi,

As for now It is not clear if this issue is related to this plugin at all or not. The line with error that you mentioned is possible [this one](https://github.com/facebook/create-react-app/blob/v4.0.3/packages/react-dev-utils/ModuleScopePlugin.js#L31). The next step to debug I suppose will be to find a line where it was called from with unexpected arguments. And so on until...

Another way is to take the example project from the `example/above` folder and modify it with minimal changes step by step to be identical to your project or until mentioned error appears. This will make it clear which change will lead to the error.

I [updated](https://github.com/oklas/react-app-rewire-alias/commit/87076d25e3f5afafcaa392b3135743897e42f8f6) deps at examples and check that it worked.

**Comment by oklas** [comment]
I also think may be you need to check your Mac for enough free space and make sure that has no malware. We tried as I mentioned on fresh Big Sur and there is no such problem with projects from `example` folder or any our work projects.

I need to reproduce the problem to solve. It is possible if you make a public repo (or share with me a private repo) with the problem. If you can not share all the code then go a second way as I suggested above to find out configuration that lead to the problem.

**Comment by oklas** [comment]
@omerts, reopen or create new issue if further details
